[site]
title = "Xing Cong"
description = "PhD student in Computer Science and Technology at Beihang University."
favicon = "/favicon.png"
last_updated = "May 27, 2026"

[author]
name = "Xing Cong"
title = "PhD Student"
institution = "Beihang University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "congxingcs@163.com"
location = "Beihang University, Haidian, Beijing"
location_details = ["Beihang University", "Haidian, Beijing, China"]
google_scholar = "https://scholar.google.com/citations?user=T8PZ3EEAAAAJ"
github = "https://github.com/xing-cong"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["en", "zh"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, the site will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
