[[news]]
date = "2026-05"
content = "RT-Lynx was accepted to ICML 2026."

[[news]]
date = "2026-05"
content = "CB-SpMV is available on arXiv."

[[news]]
date = "2025-09"
content = "Started an AI research internship at Alibaba's Technical Platform."

[[news]]
date = "2024-06"
content = "Started the direct PhD track in Computer Science and Technology at Beihang University."
