[[news]]
date = "2026-05"
content = "RT-Lynx 被 ICML 2026 接收。"

[[news]]
date = "2026-05"
content = "CB-SpMV 已发布在 arXiv。"

[[news]]
date = "2025-09"
content = "在阿里技术平台开始 AI 研究型实习。"

[[news]]
date = "2024-06"
content = "在北京航空航天大学开始计算机科学与技术硕博连读阶段学习。"
